### ISSUE TITLE
Public code release?

### ISSUE THREAD

**Issue by Tobias-Fischer** [amaralibey/MixVPR#1]
Hi @amaralibey, many thanks for your great work, your paper looks very interesting! Are you planning to make the code publicly available?

Many thanks,
Tobi

**Comment by amaralibey** [comment]
Hello @Tobias-Fischer,
Thank you for your interest, I am sorry for the delay. The code has now been published. We will soon upload the pretrained weights for all our models.
Cordially,

**Comment by Tobias-Fischer** [comment]
Thanks, Amar!
