### ISSUE TITLE
why is the skip connection executed inside the FeatureMixerLayer here?

### ISSUE THREAD

**Issue by wpumain** [amaralibey/MixVPR#13]
https://github.com/amaralibey/MixVPR/blob/31de0c35eef2c82589481293a200c9ff61741eb5/models/aggregators/mixvpr.py#L25

Why is the difference operation  skip connection inside the FeatureMixerLayer when stacking FeatureMixerLayers, instead of after stacking the FeatureMixerLayers like in ViT?

```
self.mix = nn.Sequential(*[
            FeatureMixerLayer(in_dim=hw, mlp_ratio=mlp_ratio)
            for _ in range(self.mix_depth)
        ])
```

The general practice is to execute the skip connection in the forward function after executing the above statement. However, why is the skip connection executed inside the FeatureMixerLayer here?

**Comment by amaralibey** [comment]
Hi @wpumain,


The skip connection in mixvpr.py is implemented as `[operation_on(x) + x]`, where `operation_on()` is the FeatureMixerLayer. This is the same implementation used in other models with skip connections, such as [here](https://github.com/lucidrains/vit-pytorch/blob/e1b08c15b9b237329d30324ce40579d4d4afc761/vit_pytorch/vit.py#L77) in ViT.

If you want to move the skip connection from the FeatureMixerLayer to MixVPR, you can modify the code in mixvpr.py as follows:

- Change the line `return x + self.mix(x)` in the `forward` method of FeatureMixerLayer to `return self.mix(x)`. This will remove the skip connection.
- Change the line `x = self.mix(x)` in the `forward` method of MixVPR to `for mixer_block in self.mix: x = mixer_block(x) + x`. This will apply the skip connection between each FeatureMixerLayer in MixVPR.

Both implementations are equivalent and will produce the same computational graph in PyTorch.

**Comment by wpumain** [comment]
Think you
