### ISSUE TITLE
A singleGPU will run the results, but multiple GPUs will make an error！！

### ISSUE THREAD

**Issue by Lavau** [amaralibey/MixVPR#17]
Hi，Amar Ali-bey！

Your code is so awesome. It's so concise that it appeals to me ! !

When I was training with multiple Gpus, I encountered an error, Recall@n resulting in nan.

![Snipaste_2023-04-24_14-26-00](https://user-images.githubusercontent.com/46114201/233915923-b7add244-36f7-4bff-acbf-449967b9e6fb.png)
![Snipaste_2023-04-24_14-25-39](https://user-images.githubusercontent.com/46114201/233915943-49661620-64c4-4676-9135-d68a42050436.png)
![Snipaste_2023-04-23_20-04-37](https://user-images.githubusercontent.com/46114201/233839019-868c4c51-c596-4a5c-84ab-41d0429f7905.png)

But I can use one GPU to run the project very well !!
![Snipaste_2023-04-24_14-39-39](https://user-images.githubusercontent.com/46114201/233918349-6dbf9b91-fda1-4849-b00c-7a030d8e2509.png)

So I am thinking that your code doesn't run well when somenone use multiple GPUs. Because the data is distrubuted in the multiple GPUs. 

I hope you to consider my question, then please give me an answer.

**Comment by MantangGuo** [comment]
Any further suggestions on this issue? I also encounter the same NAN situation when using multiple GPUs.
