### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by senhuangpku** [amaralibey/MixVPR#26]
Could you give me a link to download the dataset?

**Comment by amaralibey** [comment]
Hello @senhuangpku,

You can take a look at GSV-Cities repo (https://github.com/amaralibey/gsv-cities) for the Dataset and the framework for training and evaluation.

**Comment by senhuangpku** [comment]
> Hello @senhuangpku,
> 
> You can take a look at GSV-Cities repo (https://github.com/amaralibey/gsv-cities) for the Dataset and the framework for training and evaluation.

**Comment by senhuangpku** [comment]
Thanks for your reply! I have the other request is that Could you give me the links about others datasets(Nordland and SPED)?

**Comment by amaralibey** [comment]
You can find instructions in GSV-Cities repo, specifically, in this notebook: https://github.com/amaralibey/gsv-cities/blob/main/notebooks/evaluate_model.ipynb
