### ISSUE TITLE
pose estimation

### ISSUE THREAD

**Issue by cswwp** [amaralibey/MixVPR#35]
Hi @amaralibey firstly thanks for sharing so great work. I found MixVPR mainly learning global features, but no local feature, Does it means no pose estimation with MixVPR?

**Comment by hit2sjtu** [comment]
No, you have to combine mixvpr with local feature matching methods as done in [hloc](https://github.com/cvg/Hierarchical-Localization)

**Comment by cswwp** [comment]
> No, you have to combine mixvpr with local feature matching methods as done in [hloc](https://github.com/cvg/Hierarchical-Localization)

You mean add one head to do local point regression like superpose? with superpose infer result on local descriptor as another label to supervise?
