### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by gmberton** [amaralibey/MixVPR#4]
Hi @amaralibey , do you have an estimate on when the pretrained weights will be publicly available? Even only the weights of the best model would be very useful :)

**Comment by amaralibey** [comment]
Hi @gmberton,
I have released the weights for the best model alongside the code to load it. Other models will come in the coming days. Please don't hesitate to ask if you need any other specific model.
Thank you for your interest.

**Comment by gmberton** [comment]
That's great! Will you also release the model with output dimension 512? And will you release the models also for your other paper "GSV-Cities: Toward Appropriate Supervised Visual Place Recognition"?
