### ISSUE TITLE
GPU GB needed to train MixVPR

### ISSUE THREAD

**Issue by gmberton** [amaralibey/MixVPR#6]
Hello, how much GPU memory is needed to train MixVPR with the full batch size of 120 quadruplets?

**Comment by amaralibey** [comment]
Hi @gmberton,

For ResNet50 + MixVPR (4 Feature Mixers), Batch of 120 places quadruplets (480 total images of size 320x320), It uses 18.3GB of GPU Memory.

If you reduce the batch size to 100 places (400 images of size 320x320), it uses 15.3GB of GPU memory.

If you reduce the number of Feature Mixers to 1 (and keep batch size to 120), it uses 13.8GB

For ResNet18 + 4 feature Mixers + 120 Places (480 images) It uses 5.8GB of GPU memory.

**Comment by gmberton** [comment]
That was very fast, thank you!
