### ISSUE TITLE
Where can I download the  Pittsburgh-30k-test dataset ？

### ISSUE THREAD

**Issue by Eidell** [amaralibey/MixVPR#7]
can you give me the url, thank you!

**Comment by amaralibey** [comment]
Hello @Eidell,

You can request the dataset from https://github.com/Relja/netvlad by emailing Relja. 

For evaluation on the Pitts30k-test and many other benchmarks, please refer to the following tutorial in our gsv-cities repo: https://github.com/amaralibey/gsv-cities/blob/main/notebooks/evaluate_model.ipynb

Best regards,

**Comment by HuangJY503** [comment]
I have found it, the Pittsburgh dataset, the url is here: [https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/](https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/)
Besides, pitts30k_test is included in the file netvlad_v100_datasets.tar.gz.

**Comment by jxhoh** [comment]
> > 你能给我网址吗，谢谢！
> 
> 我找到了它，匹兹堡数据集，网址在这里： https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/ 此外，pitts30k_test包含在文件netvlad_v100_datasets.tar.gz中。
Can you tell me how to download these contents about pitts30k
